#!/bin/bash

if ! [ -e .lock ]; then
  echo "Nothing to do."
  exit 0
fi

source config_file

if ! [ "$1" = "-y" ]; then
  echo "Did you save the images to the registry?"
  sleep 5
  echo "You have 15 seconds to cancel if not..."
  sleep 15
fi

echo "Deleting instance!"

if [ -e .lock-stop ]; then
  gcloud compute disks delete $NAME $NAME-disk
else
  gcloud compute instances delete -q  $NAME  --delete-disks all --project   $PROJECT --zone   $ZONE
fi

rm -f .lock .lock-stop

echo "Done."
